import Header, { headerPropsType } from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";
const getHeaderData = (): headerPropsType[] => {
  return [
    {
      heading: [{ part: "Gath" }, { part: "Session" }, { part: "." }],
      navLinks: [
        {
          title: "Home",
          path: "/",
        },
        {
          title: "Features",
          path: "/features",
        },
        {
          title: "Blog",
          path: "/blog",
        },
        {
          title: "Contact",
          path: "/contact-us",
        },
        {
          title: "About Us",
          path: "/about-us",
        },
        {
          title: "Login",
          path: "/login",
        },
      ],
    },
  ];
};

export const metadata: Metadata = {
  title: "Online Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = getHeaderData();
  return (
    <html lang="en">
      <body>
        {headerData.map((header) => {
          return (
            <Header
              key={header.heading[0].part}
              heading={header.heading}
              navLinks={header.navLinks}
            />
          );
        })}

        {children}
      </body>
    </html>
  );
}
