import Header from "@/components/Header";
import { HeaderProps } from "@/types/HeaderType";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const getHeaderData = (): HeaderProps => {
  return {
    heading: ["Gath", "Session", "."],
    menuItems: ["Home", "Features", "Blog", "Contact", "About Us"],
  };
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Online Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = getHeaderData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header heading={headerData.heading} menuItems={headerData.menuItems} />
        {children}
      </body>
    </html>
  );
}
