import Header, { headerPropsType } from "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const getHeaderData = (): headerPropsType[] => {
  return [
    {
      heading: {
        part1: "Gath",
        part2: "Session",
        part3: ".",
      },
      menuItems: {
        item1: "Home",
        item2: "Features",
        item3: "Blog",
        item4: "Contact",
        item5: "About Us",
        item6: "Login"
      },
    },
  ];
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Online Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = getHeaderData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {headerData.map((header) => {
          return (
            <Header
              key={header.heading.part1}
              heading={header.heading}
              menuItems={header.menuItems}
            />
          );
        })}

        {children}
      </body>
    </html>
  );
}
